[package]
name = "creative-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.4"
log = "0.4.14"
env_logger = "0.9.0"
lazy_static = "1.4.0"
structopt = "0.3.25"
toml = "0.5.8"
serde = "1.0.130"
serde_derive = "1.0.130"