[package]
name = "persons_db"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
actix-web = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"
actix-cors = "0.1"
actix-web-httpauth = "0.3"
